-- 1. Create New Tables

CREATE TABLE IF NOT EXISTS user_exercise_preferences (
    id_user_exercise_preferences BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    id_user_details BIGINT REFERENCES user_details(id_user_details),
    id_exercise_list BIGINT REFERENCES exercises_list(id_exercise_list),
    increment_custom DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS user_exercise_rating (
    id_user_exercise_rating BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    id_user_details BIGINT REFERENCES user_details(id_user_details),
    id_exercise_list BIGINT REFERENCES exercises_list(id_exercise_list),
    rating_value SMALLINT CHECK (rating_value BETWEEN 1 AND 5),
    notes TEXT
);

CREATE TABLE IF NOT EXISTS workout_exercise_group_intensity (
    id_workout_exercise_group_intensity BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    id_program_week BIGINT REFERENCES program_weeks(id_program_week),
    type TEXT,
    name TEXT,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS workout_session (
    id_workout_session BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    id_user_details BIGINT REFERENCES user_details(id_user_details),
    id_program_week BIGINT REFERENCES program_weeks(id_program_week),
    id_program_day BIGINT REFERENCES program_days(id_program_day),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    duration_seconds INTEGER,
    mood TEXT,
    energy_level TEXT,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS program_chat_message (
    id_program_chat_message BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    id_program BIGINT REFERENCES program(id_program),
    id_user_details BIGINT REFERENCES user_details(id_user_details),
    message_text TEXT,
    attachment_url TEXT,
    is_from_trainer BOOLEAN,
    id_exercise_list BIGINT REFERENCES exercises_list(id_exercise_list)
);

CREATE TABLE IF NOT EXISTS user_weight_log (
    id_user_weight_log BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    date_measure DATE NOT NULL,
    id_user_details BIGINT REFERENCES user_details(id_user_details),
    weight_kg DOUBLE PRECISION NOT NULL,
    notes TEXT
);

-- 2. Alter Existing Tables

-- exercises_list
ALTER TABLE exercises_list ADD COLUMN IF NOT EXISTS measure_type TEXT DEFAULT 'load';
ALTER TABLE exercises_list ADD COLUMN IF NOT EXISTS increment_default DOUBLE PRECISION;
ALTER TABLE exercises_list ADD COLUMN IF NOT EXISTS joint_type TEXT DEFAULT 'multi';
ALTER TABLE exercises_list ADD COLUMN IF NOT EXISTS laterality TEXT DEFAULT 'bilateral';

-- program
ALTER TABLE program ADD COLUMN IF NOT EXISTS max_weeks SMALLINT;

-- program_weeks
ALTER TABLE program_weeks ADD COLUMN IF NOT EXISTS is_deload BOOLEAN DEFAULT FALSE;

-- program_days
ALTER TABLE program_days ADD COLUMN IF NOT EXISTS theoretical_duration_seconds INTEGER;

-- workout_day_exercises
ALTER TABLE workout_day_exercises ADD COLUMN IF NOT EXISTS order_number INTEGER;
ALTER TABLE workout_day_exercises ADD COLUMN IF NOT EXISTS notes TEXT;
-- Note: id_program_exercises removed as per new schema

-- workout_exercise_set
ALTER TABLE workout_exercise_set ADD COLUMN IF NOT EXISTS set_order INTEGER;
ALTER TABLE workout_exercise_set ADD COLUMN IF NOT EXISTS reps_min INTEGER;
ALTER TABLE workout_exercise_set ADD COLUMN IF NOT EXISTS reps_max INTEGER;
ALTER TABLE workout_exercise_set ADD COLUMN IF NOT EXISTS rest_time INTEGER;
ALTER TABLE workout_exercise_set ADD COLUMN IF NOT EXISTS target_load DOUBLE PRECISION;
ALTER TABLE workout_exercise_set ADD COLUMN IF NOT EXISTS intensity_type TEXT;
ALTER TABLE workout_exercise_set ADD COLUMN IF NOT EXISTS group_intensity_id BIGINT REFERENCES workout_exercise_group_intensity(id_workout_exercise_group_intensity);
ALTER TABLE workout_exercise_set ADD COLUMN IF NOT EXISTS actual_load DOUBLE PRECISION;
ALTER TABLE workout_exercise_set ADD COLUMN IF NOT EXISTS actual_reps INTEGER;
ALTER TABLE workout_exercise_set ADD COLUMN IF NOT EXISTS completed BOOLEAN DEFAULT FALSE;
ALTER TABLE workout_exercise_set ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;
ALTER TABLE workout_exercise_set ADD COLUMN IF NOT EXISTS notes_tracking TEXT;
ALTER TABLE workout_exercise_set ADD COLUMN IF NOT EXISTS technique_rating INTEGER;
ALTER TABLE workout_exercise_set ADD COLUMN IF NOT EXISTS id_workout_session BIGINT REFERENCES workout_session(id_workout_session);
ALTER TABLE workout_exercise_set ADD COLUMN IF NOT EXISTS id_reps_type BIGINT REFERENCES reps_types(id_reps_type);


-- 3. Data Migration

-- Migrate set_number to set_order (for existing rows only)
UPDATE workout_exercise_set SET set_order = set_number WHERE set_order IS NULL AND set_number IS NOT NULL;

-- Migrate load/reps to actual_load/actual_reps (assuming existing data is actual performance)
UPDATE workout_exercise_set SET actual_load = load WHERE actual_load IS NULL;
UPDATE workout_exercise_set SET actual_reps = reps WHERE actual_reps IS NULL;

-- Migrate prescription from workout_day_exercises to workout_exercise_set
-- This copies the exercise-level prescription to each set
UPDATE workout_exercise_set s
SET 
    reps_min = e.reps_min,
    reps_max = e.reps_max,
    rest_time = e.rest_time,
    target_load = e.target_load,
    id_reps_type = e.id_reps_type
FROM workout_day_exercises e
WHERE s.id_workout_day_exercises = e.id_workout_day_exercise
AND s.reps_min IS NULL;

-- Migrate order to order_number in workout_day_exercises
UPDATE workout_day_exercises SET order_number = "order" WHERE order_number IS NULL;
